# Generated by Django 5.2.4 on 2026-08-27 06:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedBank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("initial", models.CharField(max_length=5)),
                ("color", models.CharField(default="#7B1535", max_length=7)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("retail", "Retail"), ("corporate", "Corporate")],
                        default="corporate",
                        max_length=15,
                    ),
                ),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                ("encrypted_holder", models.TextField()),
                ("encrypted_account_number", models.TextField()),
                ("encrypted_ifsc", models.TextField()),
                ("encrypted_username", models.TextField()),
                ("encrypted_password", models.TextField()),
                (
                    "encrypted_transaction_password",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "photo_payload",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(1048576)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1 - Read Only"),
                            (2, "Level 2 - Limited Access"),
                            (3, "Level 3 - Super Admin"),
                        ],
                        default=1,
                    ),
                ),
                ("dept", models.CharField(blank=True, max_length=255)),
                ("campus", models.CharField(blank=True, max_length=255)),
                ("designation", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("user_snapshot", models.CharField(max_length=255)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=15,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
