# Generated by Django 5.2.4 on 2026-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="original_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
