# Generated by Django 5.2.4 on 2026-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0002_admin_original_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="tfa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
