# Generated by Django 5.2.4 on 2026-08-28 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0003_admin_tfa_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
