# Generated by Django 5.2.4 on 2026-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0004_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
