# Generated by Django 5.2.17 on 2026-08-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0005_admin_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedbank",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="vault_api.entity",
            ),
        ),
    ]
