# Generated by Django 5.2.4 on 2026-08-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0006_encryptedbank_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="encrypted_vault_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
