# Generated by Django 5.2.4 on 2026-08-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0007_admin_encrypted_vault_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolvedBankUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(default="corporate", max_length=15)),
                ("resolved_url", models.URLField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("bank_name", "account_type")},
            },
        ),
    ]
