# Generated by Django 5.2.4 on 2026-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0008_resolvedbankurl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResolvedBankUrl",
        ),
        migrations.AddField(
            model_name="admin",
            name="recovery_encrypted_vault_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
