# Generated by Django 5.2.4 on 2026-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vault_api", "0009_delete_resolvedbankurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["-timestamp"], name="log_timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="log_action_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["log_type"], name="log_type_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["user", "-timestamp"], name="log_user_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="admin",
            index=models.Index(fields=["name"], name="admin_name_idx"),
        ),
        migrations.AddIndex(
            model_name="admin",
            index=models.Index(fields=["is_active"], name="admin_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptedbank",
            index=models.Index(fields=["-created_at"], name="bank_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptedbank",
            index=models.Index(fields=["name"], name="bank_name_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptedbank",
            index=models.Index(fields=["account_type"], name="bank_account_type_idx"),
        ),
        migrations.AddIndex(
            model_name="encryptedbank",
            index=models.Index(
                fields=["entity", "-created_at"], name="bank_entity_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["name"], name="entity_name_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["-created_at"], name="entity_created_idx"),
        ),
    ]
