# Generated by Django 5.2.4 on 2026-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0010_alter_entity_phone_activitylog_log_timestamp_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedbank",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="encryptedbank",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="entity",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="encryptedbank",
            index=models.Index(fields=["is_deleted"], name="bank_is_deleted_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["is_deleted"], name="entity_is_deleted_idx"),
        ),
    ]
