# Generated by Django 5.2.4 on 2026-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vault_api",
            "0011_encryptedbank_deleted_at_encryptedbank_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="escrow_encrypted_vault_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
