# Generated by Django 5.2.17 on 2026-09-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0012_admin_escrow_encrypted_vault_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
