# Generated by Django 5.2.17 on 2026-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault_api", "0013_alter_entity_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedbank",
            name="encrypted_user_id_checker",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="encryptedbank",
            name="encrypted_user_id_maker",
            field=models.TextField(blank=True, null=True),
        ),
    ]
